(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-dvp)
  (meow-motion-overwrite-define-key
   '(";" . meow-quit)
   '("c" . meow-prev)
   '("t" . meow-next))
  (meow-leader-define-key
   '(";" . meow-motion-origin-command)
   '("c" . meow-motion-origin-command)
   '("t" . meow-motion-origin-command)
   '("l" . meow-goto-line))
  (meow-normal-define-key
   '("*" . meow-expand-0)
   '("=" . meow-expand-9)
   '("!" . meow-expand-8)
   '("[" . meow-expand-7)
   '("]" . meow-expand-6)
   '("{" . meow-expand-5)
   '("+" . meow-expand-4)
   '("}" . meow-expand-3)
   '(")" . meow-expand-2)
   '("(" . meow-expand-1)
   '("1" . digit-argument)
   '("2" . digit-argument)
   '("3" . digit-argument)
   '("4" . digit-argument)
   '("5" . digit-argument)
   '("6" . digit-argument)
   '("7" . digit-argument)
   '("8" . digit-argument)
   '("9" . digit-argument)
   '("0" . digit-argument)

   '(";" . meow-quit)
   '(":" . eval-expression)
   '("," . meow-reverse)
   '("<" . meow-forward-barf)
   '("." . meow-change)
   '(">" . meow-forward-slurp)
   '("p" . meow-cancel)
   '("y" . meow-grab)
   '("f" . meow-inner-of-thing)
   '("g" . meow-search)
   '("G" . meow-pop-search)
   '("c" . meow-line)
   '("C" . meow-line-expand)
   '("r" . meow-block)
   '("R" . meow-block-expand)
   '("l" . meow-visit)
   '("/" . meow-beginning-of-thing)
   '("?" . meow-cheatsheet)
   '("@" . meow-bounds-of-thing)
   '("\\" . meow-end-of-thing)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("o" . backward-delete-char)
   '("e" . meow-delete)
   '("u" . meow-undo)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("d" . meow-head)
   '("D" . meow-head-expand)
   '("h" . meow-next)
   '("H" . meow-next-expand)
   '("t" . meow-prev)
   '("T" . meow-prev-expand)
   '("n" . meow-tail)
   '("N" . meow-tail-expand)
   '("s" . meow-mark-word)
   '("S" . meow-mark-symbol)
   '("-" . negative-argument)
   '("'" . meow-pop)
   '("\"" . meow-pop-all-selection)
   '("q" . meow-kill)
   '("Q" . meow-kill-append)
   '("j" . meow-save)
   '("J" . meow-save-append)
   '("k" . meow-yank)
   '("x" . meow-replace)
   '("X" . meow-replace-save)
   '("b" . meow-join)
   '("m" . meow-back-word)
   '("M" . meow-back-symbol)
   '("w" . meow-next-word)
   '("W" . meow-next-symbol)
   '("v" . meow-find)
   '("V" . meow-find-expand)
   '("z" . meow-till)
   '("Z" . meow-till-expand))
  (setq meow-char-thing-table
        '((?a . round)
          (?o . square)
          (?e . curly)
          (?u . string)
          (?, . symbol)
          (?. . buffer)
          (?i . defun)
          (?p . indent))))

(use-package meow
  :straight
  (meow :type git
    :host github
    :repo "DogLooksGood/meow")
  :init
  (meow-global-mode 1)
  :custom
  (meow-esc-delay 0.001)
  (meow-keypad-describe-delay 0.5)
  (meow-selection-command-fallback
   '((meow-replace . meow-page-up)
     (meow-change . meow-change-char)
     (meow-save . meow-save-char)
     (meow-kill . meow-C-k)
     (meow-cancel-selection . meow-keyboard-quit)
     (meow-reverse . meow-page-down)
     (meow-delete . meow-C-d)))
  :config
  (meow-setup-line-number)
  (add-to-list 'meow-normal-state-mode-list 'inf-iex-mode)
  (add-to-list 'meow-normal-state-mode-list 'py-shell-mode)
  (add-to-list 'meow-grab-fill-commands 'eval-expression)
  (meow-setup))

(provide 'init-modal-dvp-ego)
